### ISSUE TITLE
Counter variable nomenclature

### ISSUE THREAD

**Issue by everyday847** [kcoppess/tiny_fold#3]
I suggest using doubled letters (e.g., `ii`, `jj`) for loops. It's hard to search for single letters (since they're so common!), but every occurrence of `ii` in your code will probably be the `ii` counter, not a substring of some non-English word.

**Comment by kcoppess** [comment]
Noted! I'll go through and change that.

(I'm still not use to checking this, so sorry it took a while to see this)
